"""Shared schema/key constants for simulation config and payloads."""

from __future__ import annotations

import re

from astropy import units as u

from .stats import (
    DEFAULT_STATS_EE_GEOMETRY,
    DEFAULT_STATS_FWHM_SUMMARY,
    DEFAULT_STATS_SR_METHOD,
    STATS_EE_GEOMETRIES,
    STATS_EE_GEOMETRY_ENCIRCLED,
    STATS_EE_GEOMETRY_ENSQUARED,
    STATS_FWHM_SUMMARIES,
    STATS_FWHM_SUMMARY_GEOM,
    STATS_FWHM_SUMMARY_MAX,
    STATS_FWHM_SUMMARY_MEAN,
    STATS_FWHM_SUMMARY_MIN,
    STATS_SR_METHOD_PIXEL_FIT,
    STATS_SR_METHOD_PIXEL_MAX,
    STATS_SR_METHODS,
)

# Top-level sections

KEY_SIMULATION_SECTION = "simulation"
KEY_SETUP_SECTION = "setup"
KEY_OPTION_SECTION = "options"
KEY_STATUS_SECTION = "status"
KEY_META_SECTION = "meta"
KEY_STATS_SECTION = "stats"
KEY_PSFS_SECTION = "psfs"
KEY_DIAGNOSTICS_SECTION = "diagnostics"

# Simulation config grammar keys (YAML/API-facing)

KEY_CFG_SIMULATION_BASE_PATH = "base_path"
KEY_CFG_SIMULATION_SPECIFIC_FIELDS = "specific_fields"

# Simulation payload keys (persisted `/simulation`)

KEY_SIMULATION_NAME = "name"
KEY_SIMULATION_VERSION = "version"
KEY_SIMULATION_EXTRA_STAT_FIELDS = "extra_stat_fields"
KEY_SIMULATION_NGS_MAG_STANDARD = "ngs_mag_standard"
KEY_SIMULATION_DIAGNOSTICS_LEVEL = "diagnostics_level"
KEY_SIMULATION_DIAGNOSTIC_FIELDS = "diagnostic_fields"
KEY_SIMULATION_META_FIELDS = "meta_fields"

DEFAULT_NGS_MAG_STANDARD = "R"

DIAGNOSTICS_LEVEL_NONE = "none"
DIAGNOSTICS_LEVEL_VALIDATION = "validation"
DIAGNOSTICS_LEVEL_DEBUG = "debug"
DIAGNOSTICS_LEVELS = (
    DIAGNOSTICS_LEVEL_NONE,
    DIAGNOSTICS_LEVEL_VALIDATION,
    DIAGNOSTICS_LEVEL_DEBUG,
)

# Setup config grammar keys (YAML/API-facing)

KEY_CFG_SETUP_SPECIFIC_FIELDS = "specific_fields"

# Setup payload keys

KEY_SETUP_EE_APERTURES = "ee_apertures"
KEY_SETUP_SR_METHOD = "sr_method"
KEY_SETUP_FWHM_SUMMARY = "fwhm_summary"
KEY_SETUP_EE_GEOMETRY = "ee_geometry"
KEY_SETUP_ATM_WAVELENGTH = "atm_wavelength"
KEY_SETUP_ATM_PROFILES = "atm_profiles"
KEY_SETUP_LGS_R = "lgs_r"
KEY_SETUP_LGS_THETA = "lgs_theta"
KEY_SETUP_NGS_MAGNITUDE_ZEROPOINT = "ngs_magnitude_zeropoint"
KEY_SETUP_SCI_R = "sci_r"
KEY_SETUP_SCI_THETA = "sci_theta"

# Options config grammar keys (YAML/CSV-facing)

KEY_CFG_OPTION_BROADCAST = "broadcast"
KEY_CFG_OPTION_TABLE = "table"
KEY_CFG_OPTION_TABLE_PATH = "path"
KEY_CFG_OPTION_COLUMNS = "columns"
KEY_CFG_OPTION_UNITS = "units"
KEY_CFG_OPTION_ROWS = "rows"
KEY_CFG_OPTION_NGS = "ngs"

# Options payload keys (persisted `/options`)

KEY_OPTION_WAVELENGTH = "wavelength"
KEY_OPTION_ZENITH_ANGLE = "zenith_angle"
KEY_OPTION_ATM_PROFILE_ID = "atm_profile_id"
KEY_OPTION_R0 = "r0"
KEY_OPTION_SEEING = "seeing"
KEY_OPTION_SCI_DX = "sci_dx"
KEY_OPTION_SCI_DY = "sci_dy"
KEY_OPTION_NGS_R = "ngs_r"
KEY_OPTION_NGS_THETA = "ngs_theta"
KEY_OPTION_NGS_MAGNITUDE = "ngs_magnitude"

# Runtime-derived option keys (not persisted in `/options`)

KEY_OPTION_NGS_USED = "ngs_used"

# NGS column parsing helpers

KEY_OPTION_NGS_PREFIX = "ngs_"
KEY_OPTION_R_SUFFIX = "r"
KEY_OPTION_THETA_SUFFIX = "theta"
KEY_OPTION_MAGNITUDE_SUFFIX = "magnitude"
KEY_OPTION_NGS_COLUMN_RE = re.compile(
    rf"^ngs(\d+)_({KEY_OPTION_R_SUFFIX}|{KEY_OPTION_THETA_SUFFIX}|{KEY_OPTION_MAGNITUDE_SUFFIX})$"
)

# Status/meta/stats/psfs payload keys (persisted HDF5 datasets)

KEY_STATUS_STATE = "state"

KEY_META_PIXEL_SCALE = "pixel_scale"
KEY_META_TEL_DIAMETER = "tel_diameter"
KEY_META_TEL_PUPIL = "tel_pupil"

KEY_STATS_SR = "sr"
KEY_STATS_EE = "ee"
KEY_STATS_FWHM = "fwhm"

KEY_PSFS_DATA = "data"

# Setup-controlled stats selectors are owned by ``simulation.stats`` and
# re-exported here for setup schema compatibility.

# Key collections

SIMULATION_KEYS_CORE = (
    KEY_SIMULATION_NAME,
    KEY_SIMULATION_VERSION,
    KEY_SIMULATION_EXTRA_STAT_FIELDS,
    KEY_SIMULATION_NGS_MAG_STANDARD,
)

SETUP_KEYS_CORE = (
    KEY_SETUP_EE_APERTURES,
    KEY_SETUP_SR_METHOD,
    KEY_SETUP_FWHM_SUMMARY,
    KEY_SETUP_EE_GEOMETRY,
)

OPTION_KEYS_1D = (
    KEY_OPTION_WAVELENGTH,
    KEY_OPTION_ZENITH_ANGLE,
    KEY_OPTION_ATM_PROFILE_ID,
    KEY_OPTION_R0,
)

OPTION_KEYS_NGS = (
    KEY_OPTION_NGS_R,
    KEY_OPTION_NGS_THETA,
    KEY_OPTION_NGS_MAGNITUDE,
)

OPTION_KEYS_SCI_OFFSETS = (
    KEY_OPTION_SCI_DX,
    KEY_OPTION_SCI_DY,
)

# Contract key collections

REQUIRED_SIMULATION_KEYS = SIMULATION_KEYS_CORE
REQUIRED_SETUP_KEYS = (
    KEY_SETUP_EE_APERTURES,
    KEY_SETUP_SR_METHOD,
    KEY_SETUP_FWHM_SUMMARY,
    KEY_SETUP_EE_GEOMETRY,
    KEY_SETUP_ATM_WAVELENGTH,
    KEY_SETUP_SCI_R,
    KEY_SETUP_SCI_THETA,
)
REQUIRED_OPTION_KEYS = OPTION_KEYS_1D + OPTION_KEYS_NGS

REQUIRED_GROUP_KEYS = (
    KEY_SIMULATION_SECTION,
    KEY_SETUP_SECTION,
    KEY_OPTION_SECTION,
    KEY_STATUS_SECTION,
    KEY_META_SECTION,
    KEY_STATS_SECTION,
)

REQUIRED_STATUS_KEYS = (
    KEY_STATUS_STATE,
)

REQUIRED_META_KEYS = (
    KEY_META_PIXEL_SCALE,
    KEY_META_TEL_DIAMETER,
    KEY_META_TEL_PUPIL,
)
CORE_META_KEYS = REQUIRED_META_KEYS

CORE_STATS_KEYS = (
    KEY_STATS_SR,
    KEY_STATS_EE,
    KEY_STATS_FWHM,
)
REQUIRED_STATS_KEYS = CORE_STATS_KEYS

# Canonical quantity units

SETUP_FIELD_UNITS = {
    KEY_SETUP_EE_APERTURES: u.mas,
    KEY_SETUP_ATM_WAVELENGTH: u.um,
    KEY_SETUP_LGS_R: u.arcsec,
    KEY_SETUP_LGS_THETA: u.deg,
    KEY_SETUP_NGS_MAGNITUDE_ZEROPOINT: u.photon / u.s,
    KEY_SETUP_SCI_R: u.arcsec,
    KEY_SETUP_SCI_THETA: u.deg,
}

OPTION_FIELD_UNITS = {
    KEY_OPTION_WAVELENGTH: u.um,
    KEY_OPTION_ZENITH_ANGLE: u.deg,
    KEY_OPTION_R0: u.m,
    KEY_OPTION_SEEING: u.arcsec,
    KEY_OPTION_SCI_DX: u.arcsec,
    KEY_OPTION_SCI_DY: u.arcsec,
    KEY_OPTION_NGS_R: u.arcsec,
    KEY_OPTION_NGS_THETA: u.deg,
    KEY_OPTION_NGS_MAGNITUDE: u.mag,
}

META_FIELD_UNITS = {
    KEY_META_PIXEL_SCALE: u.mas,
    KEY_META_TEL_DIAMETER: u.m,
    KEY_META_TEL_PUPIL: u.dimensionless_unscaled,
}

STATS_FIELD_UNITS = {
    KEY_STATS_SR: u.dimensionless_unscaled,
    KEY_STATS_EE: u.dimensionless_unscaled,
    KEY_STATS_FWHM: u.mas,
}

SETUP_STATS_SR_METHODS = STATS_SR_METHODS
SETUP_STATS_FWHM_SUMMARIES = STATS_FWHM_SUMMARIES
SETUP_STATS_EE_GEOMETRIES = STATS_EE_GEOMETRIES
DEFAULT_SETUP_SR_METHOD = DEFAULT_STATS_SR_METHOD
DEFAULT_SETUP_FWHM_SUMMARY = DEFAULT_STATS_FWHM_SUMMARY
DEFAULT_SETUP_EE_GEOMETRY = DEFAULT_STATS_EE_GEOMETRY
